users = [
  {first_name: "Betsy", last_name: "Pisik", uncoverage_id: "52951e6eed53308d50000001", email: "email1@gmail.com", password: "thepassword098", biography: "I love science and I’ve become fascinated with public health issues and epidemiology – cholera in Haiti, Nigerian polio, Congo’s horrifying rape culture, Vietnam’s deadly bird flu.  I have 20 years’ experience as a featurewriter, business reporter and foreign correspondent for the Washington Times.  As the paper’s U.N. bureau chief from 1996 to 2009, I reported from Congo, Ethiopia, Pakistan, Syria, Lebanon, and Israel, among other datelines.   My Iraq war coverage was nominated for a 2003 Pulitzer Prize. In 2010 I spent six weeks in northern Nigeria researching a recent polio epidemic and the international response. That story was underwritten by a grant from the Johns Hopkins-affiliated International Reporting Project, and you can read it below. Nigeria’s polio epidemic is newly noteworthy as the virus spreads across the Middle East.", photo_url: "https://uncoverageaws.s3.amazonaws.com/production/uploads/user/photo/52951e6eed53308d50000001/medium_photo_345-240x300.jpg", role: "journalist"},
  {first_name: "Sibylla", last_name: "Brodzinsky", uncoverage_id: "52051434f277c450c9000001", email: "email2@gmail.com", password: "thepassword098", biography: "Sibylla has spent more than 20 years writing about Latin American politics, human rights and social issues. She has worked and lived in Venezuela, Chile, and the Dominican Republic and currently is based in Colombia as a freelance journalist, writing regularly for The Economist, The Christian Science Monitor, and The Guardian. Her work has also appeared in TIME Magazine, The Washington Post, The Miami Herald, The Houston Chronicle, MSNBC.com, USA Today, The London Times, PODER Magazine, and on National Public Radio. Sibylla is co-editor, with Max Schoening, of Throwing Stones at the Moon (McSweeney's, 2012), a compilation of oral histories form Colombians displaced by violence, part of the Voice of Witness series. Sibylla is fully bilingual in English and Spanish and writes in both languages. She is also fluent in French and has a working knowledge of Portuguese. She holds a Bachelor of Arts degree in magazine journalism and political science from Syracuse University and studied international relations at the Ecole des Hautes Etudes Internationales in Paris.", photo_url: "https://uncoverageaws.s3.amazonaws.com/production/uploads/user/photo/52051434f277c450c9000001/medium_Sibylla_Brodzinsky_FINAL.jpg", role: "journalist"},
  {first_name: "Laura Lena", last_name: "Murray", uncoverage_id: "525dfa2887a36684d4000005", email: "email3@gmail.com", password: "thepassword098", biography: "Laura is an investigative journalist based in San Francisco, California. She is a graduate of the Stabile Center for Investigative Journalism at Columbia University after completing her bachelor’s degree in English at the University of Pennsylvania in 2007. As an undergraduate, she also studied abroad at Kings College in London and the Université François-Rabelais in Tours, France. In addition to local coverage in New York City, San Francisco and Philadelphia, she has reported on issues and events happening in Somalia, Cambodia, Guinea, DRC, Madagascar, Angola, Hong Kong and Singapore.", photo_url: "https://uncoverageaws.s3.amazonaws.com/production/uploads/user/photo/525dfa2887a36684d4000005/medium_Laura.jpg", role: "journalist"},
  {first_name: "Franceska", last_name: "Borri", uncoverage_id: "5355b0050b4a45b11d000001", email: "email4@gmail.com", password: "thepassword098", biography: "Francesca Borri, Italy 1980, holds a MA in International Relations, a MA in Human Rights, a BA in Philosophy of Law. While she was working as human rights officer, she published two books, on Kosovo and on Israel/Palestine. She turned to journalism when she realized that power players were more upset by what she was writing than by what she was doing as a jurist. She is currently covering the war in Syria.", photo_url: "https://uncoverageaws.s3.amazonaws.com/production/uploads/user/photo/5355b0050b4a45b11d000001/medium_borri2.jpg", role: "journalist"},
  {first_name: "Fred", last_name: "Schulte", uncoverage_id: "537215fe663065000c040000", email: "email5@gmail.com", password: "thepassword098", biography: "Schulte is a four-time Pulitzer Prize finalist, most recently in 2007 for a series on Baltimore’s arcane ground rent system. Schulte’s other Pulitzer-nominated projects exposed excessive heart surgery death rates in veterans’ hospitals, substandard care by health insurance plans treating low-income people and the hidden dangers of cosmetic surgery in medical offices. He spent much of his career at the Baltimore Sun and the South Florida Sun-Sentinel. Schulte has received the George Polk Award, two Investigative Reporters and Editors awards, three Gerald Loeb Awards for business writing and two Worth Bingham Prizes for investigative reporting. The University of Virginia graduate is also the author of Fleeced!, an exposé of telemarketing scams.", photo_url: "https://uncoverageaws.s3.amazonaws.com/production/uploads/user/photo/537215fe663065000c040000/medium_fred_0.jpg", role: "journalist"}
]

users.each do |hash|
  User.create(hash)
end